kumuluzee:
  name: uberapp-ride-management
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084

  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
    - name: ride-management-endpoint
      url-pattern: /v1/ride-management/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="ride-management">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="53ce6367-e595-4443-91c8-19ceb09db4c9-ls.logit.io"
                            port="12303" protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="logstash" level="trace"/>
                            </Root>
                        </Loggers>
                    </Configuration>'
app-properties:
  external-services:
    enabled: false
  healthy: true
  enable-notifications: false
